### ISSUE TITLE
Sicherstellen, dass für alle relevanten Code Systeme (LOINC, SNOMED, ICD, OPS) eine version hinterlegt ist

### ISSUE THREAD

**Issue by chgl** [bzkf/obds-to-fhir#300]
Für LOINC und SNOMED kann sie fix sein, für ICD und OPS kommt sie entweder aus oBDS oder muss ebenfalls fix gesetzt werden. Allerdings kann die ICD Version aus oBDS zB auch als "Sonstige" angegeben werden, hier ist die Frage ob man es dann als data absent setzt oder zB über das Diagnosedatum schätzt...

**Comment by chgl** [comment]
Vielleicht könnte man hier auch etwas elegantes in der application.yaml machen um Codings vor-auszufüllen und nur noch Code und Display setzen zu müssen:

```yaml
fhir:
  codings:
    loinc:
        system: "http://loinc.org"
        version: "2.80"
```

```java
@ConfigurationProperties(prefix="fhir.codings")
class Codings {
  Coding loinc;
}
```
